import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class ErrorTest27 {

    public static boolean debug = false;

    @Test
    public void test13501() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13501");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode2.calculateSum(intArray0);
        int int20 = FlawedCode2.calculateSum(intArray0);
        int int21 = FlawedCode2.calculateSum(intArray0);
        int int22 = FlawedCode3.calculateProduct(intArray0);
        int int23 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int24 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test13502() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13502");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode2.calculateSum(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double13 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test13503() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13503");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode2.calculateSum(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int16 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test13504() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13504");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode3.calculateProduct(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int18 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test13505() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13505");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode2.calculateSum(intArray0);
        int int20 = FlawedCode2.calculateSum(intArray0);
        int int21 = FlawedCode3.calculateProduct(intArray0);
        int int22 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double23 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test13506() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13506");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        int int18 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int19 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test13507() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13507");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode3.calculateProduct(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode3.calculateProduct(intArray0);
        int int20 = FlawedCode2.calculateSum(intArray0);
        int int21 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int22 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test13508() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13508");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode3.calculateProduct(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        int int18 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int19 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test13509() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13509");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode3.calculateProduct(intArray0);
        int int20 = FlawedCode3.calculateProduct(intArray0);
        int int21 = FlawedCode2.calculateSum(intArray0);
        int int22 = FlawedCode2.calculateSum(intArray0);
        int int23 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double24 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test13510() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13510");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode2.calculateSum(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double17 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test13511() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13511");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double18 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test13512() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13512");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double17 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test13513() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13513");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode3.calculateProduct(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        int int18 = FlawedCode3.calculateProduct(intArray0);
        int int19 = FlawedCode2.calculateSum(intArray0);
        int int20 = FlawedCode3.calculateProduct(intArray0);
        int int21 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int22 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test13514() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13514");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        int int18 = FlawedCode3.calculateProduct(intArray0);
        int int19 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double20 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test13515() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13515");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode3.calculateProduct(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode3.calculateProduct(intArray0);
        int int20 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int21 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test13516() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13516");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int18 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test13517() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13517");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode2.calculateSum(intArray0);
        int int20 = FlawedCode3.calculateProduct(intArray0);
        int int21 = FlawedCode2.calculateSum(intArray0);
        int int22 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int23 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test13518() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13518");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode3.calculateProduct(intArray0);
        int int20 = FlawedCode2.calculateSum(intArray0);
        int int21 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double22 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test13519() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13519");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode3.calculateProduct(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode3.calculateProduct(intArray0);
        int int20 = FlawedCode2.calculateSum(intArray0);
        int int21 = FlawedCode3.calculateProduct(intArray0);
        int int22 = FlawedCode2.calculateSum(intArray0);
        int int23 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int24 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test13520() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13520");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode2.calculateSum(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode3.calculateProduct(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double18 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test13521() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13521");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode3.calculateProduct(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        int int18 = FlawedCode3.calculateProduct(intArray0);
        int int19 = FlawedCode3.calculateProduct(intArray0);
        int int20 = FlawedCode2.calculateSum(intArray0);
        int int21 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int22 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test13522() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13522");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode3.calculateProduct(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode3.calculateProduct(intArray0);
        int int20 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int21 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test13523() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13523");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode2.calculateSum(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double11 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test13524() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13524");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode3.calculateProduct(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        int int18 = FlawedCode3.calculateProduct(intArray0);
        int int19 = FlawedCode2.calculateSum(intArray0);
        int int20 = FlawedCode2.calculateSum(intArray0);
        int int21 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double22 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test13525() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13525");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        int int18 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int19 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test13526() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13526");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double20 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test13527() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13527");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode2.calculateSum(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double17 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test13528() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13528");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double15 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test13529() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13529");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double18 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test13530() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13530");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode2.calculateSum(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int16 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test13531() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13531");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode2.calculateSum(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode3.calculateProduct(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        int int18 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int19 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test13532() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13532");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double11 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test13533() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13533");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int19 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test13534() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13534");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        int int18 = FlawedCode3.calculateProduct(intArray0);
        int int19 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double20 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test13535() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13535");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode2.calculateSum(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double15 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test13536() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13536");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int15 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test13537() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13537");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode2.calculateSum(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode2.calculateSum(intArray0);
        int int20 = FlawedCode2.calculateSum(intArray0);
        int int21 = FlawedCode3.calculateProduct(intArray0);
        int int22 = FlawedCode2.calculateSum(intArray0);
        int int23 = FlawedCode2.calculateSum(intArray0);
        int int24 = FlawedCode3.calculateProduct(intArray0);
        int int25 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int26 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test13538() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13538");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode2.calculateSum(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int15 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test13539() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13539");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int17 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test13540() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13540");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode3.calculateProduct(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        int int18 = FlawedCode3.calculateProduct(intArray0);
        int int19 = FlawedCode3.calculateProduct(intArray0);
        int int20 = FlawedCode2.calculateSum(intArray0);
        int int21 = FlawedCode2.calculateSum(intArray0);
        int int22 = FlawedCode2.calculateSum(intArray0);
        int int23 = FlawedCode3.calculateProduct(intArray0);
        int int24 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int25 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test13541() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13541");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int19 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test13542() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13542");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode3.calculateProduct(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int20 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test13543() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13543");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode2.calculateSum(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double15 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test13544() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13544");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int18 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test13545() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13545");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode2.calculateSum(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int16 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test13546() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13546");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode2.calculateSum(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int16 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test13547() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13547");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int15 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test13548() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13548");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode3.calculateProduct(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        int int18 = FlawedCode3.calculateProduct(intArray0);
        int int19 = FlawedCode3.calculateProduct(intArray0);
        int int20 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double21 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test13549() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13549");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode3.calculateProduct(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int19 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test13550() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest27.test13550");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode3.calculateProduct(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        int int18 = FlawedCode3.calculateProduct(intArray0);
        int int19 = FlawedCode2.calculateSum(intArray0);
        int int20 = FlawedCode2.calculateSum(intArray0);
        int int21 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double22 = FlawedCode4.calculateAverage(intArray0);
    }
}

