import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class ErrorTest19 {

    public static boolean debug = false;

    @Test
    public void test9501() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9501");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode2.calculateSum(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int12 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test9502() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9502");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int19 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test9503() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9503");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double15 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9504() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9504");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode3.calculateProduct(intArray0);
        int int20 = FlawedCode3.calculateProduct(intArray0);
        int int21 = FlawedCode3.calculateProduct(intArray0);
        int int22 = FlawedCode3.calculateProduct(intArray0);
        int int23 = FlawedCode2.calculateSum(intArray0);
        int int24 = FlawedCode3.calculateProduct(intArray0);
        int int25 = FlawedCode3.calculateProduct(intArray0);
        int int26 = FlawedCode3.calculateProduct(intArray0);
        int int27 = FlawedCode2.calculateSum(intArray0);
        int int28 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double29 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9505() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9505");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double17 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9506() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9506");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode2.calculateSum(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode2.calculateSum(intArray0);
        int int20 = FlawedCode2.calculateSum(intArray0);
        int int21 = FlawedCode2.calculateSum(intArray0);
        int int22 = FlawedCode2.calculateSum(intArray0);
        int int23 = FlawedCode2.calculateSum(intArray0);
        int int24 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double25 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9507() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9507");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode2.calculateSum(intArray0);
        int int20 = FlawedCode3.calculateProduct(intArray0);
        int int21 = FlawedCode3.calculateProduct(intArray0);
        int int22 = FlawedCode2.calculateSum(intArray0);
        int int23 = FlawedCode3.calculateProduct(intArray0);
        int int24 = FlawedCode2.calculateSum(intArray0);
        int int25 = FlawedCode3.calculateProduct(intArray0);
        int int26 = FlawedCode2.calculateSum(intArray0);
        int int27 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int28 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test9508() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9508");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double19 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9509() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9509");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int18 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test9510() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9510");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode2.calculateSum(intArray0);
        int int20 = FlawedCode2.calculateSum(intArray0);
        int int21 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double22 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9511() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9511");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode3.calculateProduct(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode3.calculateProduct(intArray0);
        int int20 = FlawedCode2.calculateSum(intArray0);
        int int21 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int22 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test9512() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9512");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode2.calculateSum(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode3.calculateProduct(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double18 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9513() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9513");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode2.calculateSum(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode3.calculateProduct(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int19 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test9514() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9514");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode2.calculateSum(intArray0);
        int int20 = FlawedCode2.calculateSum(intArray0);
        int int21 = FlawedCode2.calculateSum(intArray0);
        int int22 = FlawedCode3.calculateProduct(intArray0);
        int int23 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double24 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9515() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9515");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode2.calculateSum(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double14 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9516() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9516");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int15 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test9517() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9517");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double10 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9518() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9518");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int16 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test9519() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9519");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode2.calculateSum(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double17 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9520() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9520");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int11 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test9521() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9521");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode2.calculateSum(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode3.calculateProduct(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int20 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test9522() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9522");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode2.calculateSum(intArray0);
        int int20 = FlawedCode3.calculateProduct(intArray0);
        int int21 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int22 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test9523() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9523");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        int int18 = FlawedCode3.calculateProduct(intArray0);
        int int19 = FlawedCode3.calculateProduct(intArray0);
        int int20 = FlawedCode3.calculateProduct(intArray0);
        int int21 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double22 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9524() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9524");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode3.calculateProduct(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode3.calculateProduct(intArray0);
        int int20 = FlawedCode3.calculateProduct(intArray0);
        int int21 = FlawedCode2.calculateSum(intArray0);
        int int22 = FlawedCode2.calculateSum(intArray0);
        int int23 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int24 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test9525() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9525");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode3.calculateProduct(intArray0);
        int int20 = FlawedCode2.calculateSum(intArray0);
        int int21 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double22 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9526() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9526");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode2.calculateSum(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode3.calculateProduct(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double18 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9527() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9527");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode2.calculateSum(intArray0);
        int int20 = FlawedCode2.calculateSum(intArray0);
        int int21 = FlawedCode2.calculateSum(intArray0);
        int int22 = FlawedCode2.calculateSum(intArray0);
        int int23 = FlawedCode3.calculateProduct(intArray0);
        int int24 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double25 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9528() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9528");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int20 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test9529() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9529");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double20 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9530() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9530");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode3.calculateProduct(intArray0);
        int int20 = FlawedCode3.calculateProduct(intArray0);
        int int21 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double22 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9531() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9531");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode3.calculateProduct(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        int int18 = FlawedCode3.calculateProduct(intArray0);
        int int19 = FlawedCode2.calculateSum(intArray0);
        int int20 = FlawedCode2.calculateSum(intArray0);
        int int21 = FlawedCode2.calculateSum(intArray0);
        int int22 = FlawedCode3.calculateProduct(intArray0);
        int int23 = FlawedCode3.calculateProduct(intArray0);
        int int24 = FlawedCode2.calculateSum(intArray0);
        int int25 = FlawedCode2.calculateSum(intArray0);
        int int26 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double27 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9532() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9532");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode2.calculateSum(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int18 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test9533() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9533");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode2.calculateSum(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode3.calculateProduct(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        int int18 = FlawedCode3.calculateProduct(intArray0);
        int int19 = FlawedCode2.calculateSum(intArray0);
        int int20 = FlawedCode3.calculateProduct(intArray0);
        int int21 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int22 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test9534() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9534");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode2.calculateSum(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode3.calculateProduct(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double18 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9535() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9535");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode2.calculateSum(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode2.calculateSum(intArray0);
        int int20 = FlawedCode2.calculateSum(intArray0);
        int int21 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double22 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9536() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9536");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode2.calculateSum(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int13 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test9537() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9537");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode2.calculateSum(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode3.calculateProduct(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        int int18 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double19 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9538() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9538");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode3.calculateProduct(intArray0);
        int int20 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int21 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test9539() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9539");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double14 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9540() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9540");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int10 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test9541() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9541");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        int int18 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double19 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9542() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9542");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double11 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9543() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9543");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode3.calculateProduct(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        int int18 = FlawedCode3.calculateProduct(intArray0);
        int int19 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int20 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test9544() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9544");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode3.calculateProduct(intArray0);
        int int20 = FlawedCode3.calculateProduct(intArray0);
        int int21 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double22 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9545() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9545");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode2.calculateSum(intArray0);
        int int20 = FlawedCode2.calculateSum(intArray0);
        int int21 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int22 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test9546() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9546");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        int int18 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double19 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9547() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9547");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode3.calculateProduct(intArray0);
        int int20 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double21 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9548() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9548");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode3.calculateProduct(intArray0);
        int int20 = FlawedCode3.calculateProduct(intArray0);
        int int21 = FlawedCode2.calculateSum(intArray0);
        int int22 = FlawedCode2.calculateSum(intArray0);
        int int23 = FlawedCode2.calculateSum(intArray0);
        int int24 = FlawedCode2.calculateSum(intArray0);
        int int25 = FlawedCode2.calculateSum(intArray0);
        int int26 = FlawedCode2.calculateSum(intArray0);
        int int27 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int28 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test9549() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9549");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode2.calculateSum(intArray0);
        int int20 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double21 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9550() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9550");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode2.calculateSum(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double12 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9551() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9551");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode3.calculateProduct(intArray0);
        int int20 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int21 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test9552() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9552");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int19 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test9553() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9553");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode3.calculateProduct(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int18 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test9554() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9554");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double12 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9555() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9555");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        int int18 = FlawedCode3.calculateProduct(intArray0);
        int int19 = FlawedCode2.calculateSum(intArray0);
        int int20 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int21 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test9556() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9556");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double13 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9557() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9557");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double14 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9558() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9558");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode2.calculateSum(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int16 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test9559() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9559");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode2.calculateSum(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double12 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9560() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9560");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode3.calculateProduct(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        int int18 = FlawedCode3.calculateProduct(intArray0);
        int int19 = FlawedCode2.calculateSum(intArray0);
        int int20 = FlawedCode3.calculateProduct(intArray0);
        int int21 = FlawedCode2.calculateSum(intArray0);
        int int22 = FlawedCode3.calculateProduct(intArray0);
        int int23 = FlawedCode3.calculateProduct(intArray0);
        int int24 = FlawedCode2.calculateSum(intArray0);
        int int25 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double26 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9561() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9561");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode3.calculateProduct(intArray0);
        int int20 = FlawedCode2.calculateSum(intArray0);
        int int21 = FlawedCode3.calculateProduct(intArray0);
        int int22 = FlawedCode2.calculateSum(intArray0);
        int int23 = FlawedCode3.calculateProduct(intArray0);
        int int24 = FlawedCode3.calculateProduct(intArray0);
        int int25 = FlawedCode2.calculateSum(intArray0);
        int int26 = FlawedCode2.calculateSum(intArray0);
        int int27 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double28 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9562() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9562");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode3.calculateProduct(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        int int18 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int19 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test9563() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9563");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode2.calculateSum(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double17 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9564() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9564");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double17 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9565() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9565");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode2.calculateSum(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double17 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9566() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9566");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        int int18 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int19 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test9567() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9567");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode3.calculateProduct(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        int int18 = FlawedCode3.calculateProduct(intArray0);
        int int19 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int20 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test9568() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9568");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode3.calculateProduct(intArray0);
        int int20 = FlawedCode2.calculateSum(intArray0);
        int int21 = FlawedCode3.calculateProduct(intArray0);
        int int22 = FlawedCode2.calculateSum(intArray0);
        int int23 = FlawedCode2.calculateSum(intArray0);
        int int24 = FlawedCode2.calculateSum(intArray0);
        int int25 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int26 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test9569() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9569");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode3.calculateProduct(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        int int18 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double19 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9570() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9570");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode2.calculateSum(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double18 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9571() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9571");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode2.calculateSum(intArray0);
        int int20 = FlawedCode3.calculateProduct(intArray0);
        int int21 = FlawedCode2.calculateSum(intArray0);
        int int22 = FlawedCode3.calculateProduct(intArray0);
        int int23 = FlawedCode3.calculateProduct(intArray0);
        int int24 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int25 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test9572() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9572");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double11 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9573() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9573");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode3.calculateProduct(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        int int18 = FlawedCode3.calculateProduct(intArray0);
        int int19 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int20 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test9574() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9574");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        int int18 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int19 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test9575() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9575");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode2.calculateSum(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double13 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9576() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9576");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double17 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9577() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9577");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode3.calculateProduct(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode3.calculateProduct(intArray0);
        int int20 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double21 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9578() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9578");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int20 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test9579() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9579");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode2.calculateSum(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode3.calculateProduct(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double18 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9580() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9580");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode2.calculateSum(intArray0);
        int int20 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int21 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test9581() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9581");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double18 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9582() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9582");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode3.calculateProduct(intArray0);
        int int20 = FlawedCode2.calculateSum(intArray0);
        int int21 = FlawedCode3.calculateProduct(intArray0);
        int int22 = FlawedCode3.calculateProduct(intArray0);
        int int23 = FlawedCode2.calculateSum(intArray0);
        int int24 = FlawedCode3.calculateProduct(intArray0);
        int int25 = FlawedCode3.calculateProduct(intArray0);
        int int26 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int27 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test9583() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9583");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode3.calculateProduct(intArray0);
        int int20 = FlawedCode3.calculateProduct(intArray0);
        int int21 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int22 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test9584() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9584");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode2.calculateSum(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double20 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9585() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9585");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode2.calculateSum(intArray0);
        int int18 = FlawedCode2.calculateSum(intArray0);
        int int19 = FlawedCode2.calculateSum(intArray0);
        int int20 = FlawedCode2.calculateSum(intArray0);
        int int21 = FlawedCode2.calculateSum(intArray0);
        int int22 = FlawedCode2.calculateSum(intArray0);
        int int23 = FlawedCode3.calculateProduct(intArray0);
        int int24 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int25 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test9586() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9586");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode3.calculateProduct(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double18 = FlawedCode4.calculateAverage(intArray0);
    }

    @Test
    public void test9587() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9587");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode2.calculateSum(intArray0);
        int int3 = FlawedCode2.calculateSum(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode2.calculateSum(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        int int18 = FlawedCode3.calculateProduct(intArray0);
        int int19 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int20 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test9588() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9588");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode2.calculateSum(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int14 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test9589() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9589");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode3.calculateProduct(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode2.calculateSum(intArray0);
        int int7 = FlawedCode2.calculateSum(intArray0);
        int int8 = FlawedCode2.calculateSum(intArray0);
        int int9 = FlawedCode3.calculateProduct(intArray0);
        int int10 = FlawedCode3.calculateProduct(intArray0);
        int int11 = FlawedCode3.calculateProduct(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode3.calculateProduct(intArray0);
        int int14 = FlawedCode2.calculateSum(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        int int15 = FlawedCode5.findMaximum(intArray0);
    }

    @Test
    public void test9590() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest19.test9590");
        int[] intArray0 = new int[] {};
        int int1 = FlawedCode2.calculateSum(intArray0);
        int int2 = FlawedCode3.calculateProduct(intArray0);
        int int3 = FlawedCode3.calculateProduct(intArray0);
        int int4 = FlawedCode2.calculateSum(intArray0);
        int int5 = FlawedCode3.calculateProduct(intArray0);
        int int6 = FlawedCode3.calculateProduct(intArray0);
        int int7 = FlawedCode3.calculateProduct(intArray0);
        int int8 = FlawedCode3.calculateProduct(intArray0);
        int int9 = FlawedCode2.calculateSum(intArray0);
        int int10 = FlawedCode2.calculateSum(intArray0);
        int int11 = FlawedCode2.calculateSum(intArray0);
        int int12 = FlawedCode3.calculateProduct(intArray0);
        int int13 = FlawedCode2.calculateSum(intArray0);
        int int14 = FlawedCode3.calculateProduct(intArray0);
        int int15 = FlawedCode2.calculateSum(intArray0);
        int int16 = FlawedCode2.calculateSum(intArray0);
        int int17 = FlawedCode3.calculateProduct(intArray0);
        // during test generation this statement threw an exception of type java.lang.ArrayIndexOutOfBoundsException in error
        double double18 = FlawedCode4.calculateAverage(intArray0);
    }
}

